language: rust
cache: cargo
rust:
  - stable
  - beta
  #- nightly
  - 1.39.0
jobs:
  include:
    - rust: 1.39.0
      env: TEST_MINIMAL_VERSIONS=1
matrix:
  allow_failures:
    - rust: nightly
script:
  - |
    if [ "${TEST_MINIMAL_VERSIONS:-0}" -ne 0 ] ; then
        rustup install nightly
        cargo +nightly update -Z minimal-versions
    fi
  - cargo build --verbose --workspace --all-features
  - cargo test --verbose --workspace --all-features
notifications:
  email: false
